package com.bookshop.dto;

import com.bookshop.entity.Product;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
// OOP CONCEPT: ENCAPSULATION
// The fields below are private, meaning their data is protected from outside interference.
// They can only be accessed or modified using the public getter and setter methods generated by the @Data annotation.
public class WishlistDTO {
    private String id;
    private String userId;
    private List<Product> items;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
